apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatsby-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: https://github.com/jzr1991/gatsby-simple-container
    targetRevision: develop